plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

version = project.version
group = project.group
base { archivesName = project.archives_base_name }

repositories {
	maven { name = 'AliyunPublic'; url = 'https://maven.aliyun.com/repository/public' }
	maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	// 用 Mojang 官方映射 —— 本机 ref\client-1.21.11-mojmap.txt 即由此而来
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version
	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	it.options.encoding = 'UTF-8'
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}" }
	}
}
